# Copyright (C) 2023 Adam K Dean <adamkdean@googlemail.com>
# Use of this source code is governed by the GPL-3.0
# license that can be found in the LICENSE file.

FROM python:3.8-slim-buster

WORKDIR /app

ADD crontab /etc/cron.d/hourly-job
RUN chmod 0644 /etc/cron.d/hourly-job
RUN touch /var/log/cron.log

RUN apt-get update
RUN apt-get -y install cron

COPY python /app
RUN pip install --no-cache-dir -r requirements.txt

CMD cron && tail -f /var/log/cron.log
